# =============================================================================
# MyPlayer — Production ProGuard / R8 Rules
# =============================================================================
# Generated by security hardening Phase 1.
# All rules are commented to explain WHY they exist.
# =============================================================================

# ── Strip source file names and line numbers from release stack traces ────────
# WHY: Prevents attackers from reconstructing exact source locations.
-renamesourcefileattribute SourceFile
# Keep line numbers ONLY if you need crash reporting (e.g., Firebase Crashlytics).
# Uncomment the next line if you use Crashlytics and want readable stack traces:
# -keepattributes SourceFile,LineNumberTable

# ── Aggressive optimisation passes ────────────────────────────────────────────
# WHY: More passes = smaller + harder to read bytecode.
-optimizationpasses 5
-allowaccessmodification
-repackageclasses ''           # Moves all classes into the root package, hiding structure
-mergeinterfacesaggressively
-overloadaggressively          # Overloads methods with same signature to confuse decompilers

# ── Remove all Log calls from release builds ──────────────────────────────────
# WHY: Log.d/i/e/w leak internal class names, stack paths, and sensitive data.
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int d(...);
    public static int i(...);
    public static int w(...);
    public static int e(...);
    public static int wtf(...);
}

# =============================================================================
# ── KOTLIN ────────────────────────────────────────────────────────────────────
# =============================================================================
-keep class kotlin.Metadata { *; }
-keepclassmembers class **$Companion {
    public synthetic <methods>;
}
-keepclassmembers class * {
    @kotlin.jvm.JvmStatic <methods>;
    @kotlin.jvm.JvmField <fields>;
}
-dontwarn kotlin.**
-dontwarn kotlinx.**

# Keep coroutine internals (required for suspend function dispatch)
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# =============================================================================
# ── HILT / DAGGER ─────────────────────────────────────────────────────────────
# =============================================================================
# WHY: Hilt generates code at compile time; renaming breaks DI injection.
-keep class dagger.hilt.** { *; }
-keep class dagger.** { *; }
-keep class javax.inject.** { *; }
-keepclassmembers class * {
    @javax.inject.Inject <fields>;
    @javax.inject.Inject <init>(...);
    @dagger.hilt.android.AndroidEntryPoint *;
}
-keep @dagger.hilt.android.AndroidEntryPoint class * { *; }
-keep @dagger.hilt.android.HiltAndroidApp class * { *; }
-keep @dagger.Module class * { *; }
-keep @dagger.hilt.InstallIn class * { *; }
-keep class **_HiltComponents* { *; }
-keep class **_MembersInjector* { *; }
-keep class **_Factory* { *; }
-keep class **Hilt_* { *; }
-dontwarn dagger.**

# =============================================================================
# ── ROOM DATABASE ─────────────────────────────────────────────────────────────
# =============================================================================
# WHY: Room uses reflection to read @Entity/@Dao annotations at runtime.
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao interface * { *; }
-keep @androidx.room.Database class * { *; }
-keepclassmembers @androidx.room.Entity class * { *; }
-keepclassmembers @androidx.room.Embedded class * { *; }
-keepclassmembers @androidx.room.Relation class * { *; }
-dontwarn androidx.room.**

# =============================================================================
# ── MEDIA3 / EXOPLAYER ────────────────────────────────────────────────────────
# =============================================================================
-keep class androidx.media3.** { *; }
-keep class androidx.media.** { *; }
-keep interface androidx.media3.** { *; }
-dontwarn androidx.media3.**
-dontwarn com.google.android.exoplayer2.**

# =============================================================================
# ── OKHTTP / OKIO ─────────────────────────────────────────────────────────────
# =============================================================================
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keepattributes Signature
-keepattributes *Annotation*

# =============================================================================
# ── KOTLINX SERIALIZATION ────────────────────────────────────────────────────
# =============================================================================
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class * {
    @kotlinx.serialization.Serializable <fields>;
}
-keep @kotlinx.serialization.Serializable class * { *; }
-keep class kotlinx.serialization.** { *; }

# =============================================================================
# ── NEWPIPE EXTRACTOR ────────────────────────────────────────────────────────
# =============================================================================
-keep class org.schabi.newpipe.** { *; }
-keep interface org.schabi.newpipe.** { *; }
-dontwarn org.schabi.newpipe.**
-dontwarn org.mozilla.javascript.**
-dontwarn org.apache.**

# =============================================================================
# ── COIL IMAGE LOADING ────────────────────────────────────────────────────────
# =============================================================================
-dontwarn coil.**
-keep class coil.** { *; }

# =============================================================================
# ── ANDROIDX / ANDROID ───────────────────────────────────────────────────────
# =============================================================================
-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep class * extends android.app.Activity
-keep class * extends android.app.Service
-keep class * extends android.content.BroadcastReceiver
-keep class * extends android.content.ContentProvider
-keep class * extends android.app.Application
-keep class * extends androidx.work.Worker
-keep class * extends androidx.work.CoroutineWorker
-keep class * extends androidx.work.ListenableWorker {
    public <init>(android.content.Context, androidx.work.WorkerParameters);
}
-keep @androidx.hilt.work.HiltWorker class * { *; }
-dontwarn androidx.lifecycle.**
-dontwarn androidx.work.**

# =============================================================================
# ── WORKMANAGER ───────────────────────────────────────────────────────────────
# =============================================================================
-keep class androidx.work.** { *; }

# =============================================================================
# ── NAVIGATION / COMPOSE ──────────────────────────────────────────────────────
# =============================================================================
-keep class androidx.navigation.** { *; }
-dontwarn androidx.compose.**

# =============================================================================
# ── SECURITY LAYER (our own) ─────────────────────────────────────────────────
# =============================================================================
# WHY: JNI bridge methods MUST keep their exact names — JVM looks them up by
#      exact name when loading the native library.
-keepclassmembers class com.example.myplayer.security.SecurityNativeBridge {
    native <methods>;
}
# Keep security managers so Hilt can inject them.
-keep class com.example.myplayer.security.** { *; }

# =============================================================================
# ── PLAY INTEGRITY ────────────────────────────────────────────────────────────
# =============================================================================
-keep class com.google.android.play.** { *; }
-dontwarn com.google.android.play.**

# =============================================================================
# ── ENCRYPTED SHARED PREFERENCES ─────────────────────────────────────────────
# =============================================================================
-keep class androidx.security.crypto.** { *; }
-dontwarn androidx.security.crypto.**

# =============================================================================
# ── MISCELLANEOUS ────────────────────────────────────────────────────────────
# =============================================================================
# Preserve generic type information (needed by Gson / Retrofit if added later)
-keepattributes Signature
# Suppress warnings for missing classes in dependencies
-dontwarn com.google.errorprone.**
-dontwarn sun.misc.**
-dontwarn java.lang.invoke.**